version: '3.8'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  orchestrator:
    build: ../src/orchestrator
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - AGENT_MANAGER_URL=http://agent_manager:5002
      - KNOWLEDGE_GRAPH_URL=http://knowledge_graph_mock:5003
      - MEMORY_LAYER_URL=http://memory_layer:5004
      - EXECUTION_SANDBOX_URL=http://execution_sandbox:5005
      - LLM_ADAPTER_URL=http://llm_adapter_mock:5006
    depends_on:
      - agent_manager
      - knowledge_graph_mock
      - memory_layer
      - execution_sandbox
      - llm_adapter_mock

  agent_manager:
    build: ../src/agent_manager
    ports:
      - "5002:5002"

  knowledge_graph_mock:
    build: ../src/knowledge_graph_mock
    ports:
      - "5003:5003"

  memory_layer:
    build: ../src/memory_layer
    ports:
      - "5004:5004"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  execution_sandbox:
    build: ../src/execution_sandbox
    ports:
      - "5005:5005"

  llm_adapter_mock:
    build: ../src/llm_adapter_mock
    ports:
      - "5006:5006"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY} # Pass the API key from the host