apiVersion: v1
kind: Namespace
metadata:
  name: nexus-production
  labels:
    istio-injection: enabled
    monitoring: enabled

---
# ConfigMap for environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-config
  namespace: nexus-production
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  PROMETHEUS_URL: "http://prometheus.nexus-observability.svc.cluster.local:9090"
  JAEGER_ENDPOINT: "http://jaeger-collector.nexus-observability.svc.cluster.local:14268/api/traces"
  NEO4J_URI: "bolt://neo4j.nexus-data.svc.cluster.local:7687"
  REDIS_URL: "redis://redis.nexus-data.svc.cluster.local:6379"

---
# Secret for sensitive data (to be created manually)
apiVersion: v1
kind: Secret
metadata:
  name: nexus-secrets
  namespace: nexus-production
type: Opaque
data:
  # These values are populated by running the ./create-secrets.sh script.
  # Do not commit sensitive data to this file.
  OPENAI_API_KEY: ""
  NEO4J_PASSWORD: ""

---
# Meta-Controller Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meta-controller
  namespace: nexus-production
  labels:
    app: nexus
    component: meta-controller
    version: v2.0.0
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nexus
      component: meta-controller
  template:
    metadata:
      labels:
        app: nexus
        component: meta-controller
        version: v2.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: nexus-meta-controller # Assumes a service account exists
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: meta-controller
        image: nexus-registry/nexus-meta-controller:2.0.0 # Replace with your actual registry/image
        imagePullPolicy: Always
        ports:
        - containerPort: 6000
          name: http
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        envFrom:
        - configMapRef:
            name: nexus-config
        - secretRef:
            name: nexus-secrets
        resources:
          requests:
            cpu: "1000m"
            memory: "2Gi"
          limits:
            cpu: "4000m"
            memory: "8Gi"
        livenessProbe:
          httpGet:
            path: /healthz # Assuming a health check endpoint
            port: 6000
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz # Assuming a readiness endpoint
            port: 6000
          initialDelaySeconds: 30
          periodSeconds: 5
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}

---
# HorizontalPodAutoscaler for Meta-Controller
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: meta-controller-hpa
  namespace: nexus-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: meta-controller
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30

---
# Service for Meta-Controller
apiVersion: v1
kind: Service
metadata:
  name: meta-controller
  namespace: nexus-production
  labels:
    app: nexus
    component: meta-controller
spec:
  type: ClusterIP
  selector:
    app: nexus
    component: meta-controller
  ports:
  - name: http
    port: 6000
    targetPort: 6000
  - name: metrics
    port: 9090
    targetPort: 9090

---
# VirtualService for Istio traffic management
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: meta-controller
  namespace: nexus-production
spec:
  hosts:
  - meta-controller.nexus-production.svc.cluster.local
  http:
  - route:
    - destination:
        host: meta-controller
        subset: stable
      weight: 100
    timeout: 30s
    retries:
      attempts: 3
      perTryTimeout: 10s
      retryOn: 5xx,reset,connect-failure,refused-stream

---
# DestinationRule for traffic policies
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: meta-controller
  namespace: nexus-production
spec:
  host: meta-controller
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1000
      http:
        http1MaxPendingRequests: 100
    outlierDetection:
      consecutiveErrors: 5
      interval: 30s
      baseEjectionTime: 30s
  subsets:
  - name: stable
    labels:
      version: v2.0.0
  - name: canary
    labels:
      version: v2.1.0 # For future canary deployments

---
# PodDisruptionBudget for high availability
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: meta-controller-pdb
  namespace: nexus-production
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: nexus
      component: meta-controller

---
# NetworkPolicy for security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: meta-controller-netpol
  namespace: nexus-production
spec:
  podSelector:
    matchLabels:
      app: nexus
      component: meta-controller
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    # Allow traffic from other pods in the same namespace (e.g., from an ingress gateway)
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 6000
  egress:
  # Allow egress to other NEXUS services and the observability stack
  - to:
    - namespaceSelector:
        matchLabels:
          name: nexus-production
    - namespaceSelector:
        matchLabels:
          name: nexus-observability
    - namespaceSelector:
        matchLabels:
          name: nexus-data
  # Allow egress for DNS
  - ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53